sudo: required

language: generic

services:
 - docker

if: tag IS present

script:
 - docker build -t cryptofacilities/bitcoin-abc:${TRAVIS_TAG} .
 - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
 - docker push cryptofacilities/bitcoin-abc:${TRAVIS_TAG}
